export enum ErrorMessage {
  USER_EXISTS = 'USER_EXISTS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  MISSING_TOKEN = 'MISSING_TOKEN',
  EMAIL_OR_PASSWORD_WRONG = 'EMAIL_OR_PASSWORD_WRONG'
}
